### ISSUE TITLE
Message that Redshift backend doesn't support "inline editing"

### ISSUE THREAD

**Issue by ujovlado** [keboola/storage-api-console#15]
Ozrejmim v PR, len zakladam aby sa nezabudlo.

**Comment by ondrejhlavacek** [comment]
potřebujeme ten inline editing nutně?

**Comment by ujovlado** [comment]
@ondrejhlavacek tak mne by sa tiez pacilo, keby sme to mohli vyhodit (lebo funguje/nefunguje to len v specifickych pripadoch) ... akurat mam pocit, ze ti useri, co si uz na to zvykli a pouzivaju to, nebudu nadseni.

A tiez potom, co s komponentami, ktore sa prave edituju cez to? (youtube extractor v2 napr.)

**Comment by ondrejhlavacek** [comment]
Sys buckety můžeme omezit na mysql než je vyhodime úplně. Redshift se na ně
nehodí vůbec

**Comment by ujovlado** [comment]
@ondrejhlavacek ked uz nebudu `sys` buckety, mozeme ho odprasit, bol len na ne. zatial by som tam nehal tu hlasku.

**Comment by ujovlado** [comment]
ten PR som zavrel, toto stale je issue ... ale coskoro nebude.
