### ISSUE TITLE
Wrong "data size"

### ISSUE THREAD

**Issue by ujovlado** [keboola/storage-api-console#16]
3 rows and data size 12MB?

![screenshot_2016-03-31_11-50-32](https://cloud.githubusercontent.com/assets/419849/14172144/deb2db14-f736-11e5-99e2-46fe9f63426b.png)

**Comment by Halama** [comment]
je to redshift backend?

**Comment by ujovlado** [comment]
@Halama ano

**Comment by ujovlado** [comment]
ok for RS backend
