### ISSUE TITLE
Buckets sharing - fix typo

### ISSUE THREAD

**Issue by ErikZigo** [keboola/storage-api-console#20]
![image](https://cloud.githubusercontent.com/assets/1726727/21769113/5a2b34be-d67d-11e6-9638-d9b25701c56a.png)
![image](https://cloud.githubusercontent.com/assets/1726727/21769153/841db076-d67d-11e6-9f49-4dbf5429b991.png)

**Comment by ujovlado** [comment]
Already fixed
