### ISSUE TITLE
Hovering token causes error

### ISSUE THREAD

**Issue by ujovlado** [keboola/storage-api-console#21]
Move mouse here:

![screenshot_2017-02-21_20-54-57](https://cloud.githubusercontent.com/assets/419849/23182316/6a807460-f878-11e6-8045-9bbcbdc14ec3.png)

Check console:

![screenshot_2017-02-21_20-55-08](https://cloud.githubusercontent.com/assets/419849/23182281/488ef89a-f878-11e6-889e-c3aa456d9755.png)

**Comment by Halama** [comment]
to bude flash kopirovadlo. Tokeny z ni pujdou pryc jako prvni tak tim se to vyresi

**Comment by ujovlado** [comment]
Nemam flash, nemam token :smile: 
![screenshot_2017-07-17_16-30-23](https://user-images.githubusercontent.com/419849/28272961-50389bde-6b0d-11e7-97ef-30e87272fb84.png)
