### ISSUE TITLE
Don't allow credentials creation for buckets

### ISSUE THREAD

**Issue by ujovlado** [keboola/storage-api-console#30]
![snimek obrazovky 2017-08-14 v 15 12 44](https://user-images.githubusercontent.com/419849/29283685-09111cdc-8128-11e7-9bab-79275cd831c9.png)

**Comment by pivnicek** [comment]
why not?  It is a redshift-only feature, but I'm curious about your reason :)

**Comment by Halama** [comment]
it is deprecated, and it must be turned off

**Comment by Halama** [comment]
but, it wasn't officially deprecated http://docs.keboola.apiary.io/#reference/buckets-credentials
I'll do this later.

**Comment by pivnicek** [comment]
ic, didn't know it was deprecated.  cheers.

**Comment by Halama** [comment]
It is same like custom SQL aliases, it must go away because it complicates migrations to other backend and it leaks internal structure so it is hard to do some changes.
