### ISSUE TITLE
don load shared buckets if using token with restricted permissions 

### ISSUE THREAD

**Issue by kacurez** [keboola/storage-api-console#31]
1. vytvorim si token a nastavim len `read(alebo write)` pravo na jeden bucket
2. kliknem na `Check token in console`
![image](https://user-images.githubusercontent.com/1412120/30921931-ff0d2562-a3a7-11e7-878a-81b5cddbd50f.png)
3. dostanem chybu `You don't have access to the resource.`
![image](https://user-images.githubusercontent.com/1412120/30921959-0ea5cd08-a3a8-11e7-9055-16d49c2828c4.png)
failne to na api calle `GET https://connection.keboola.com/v2/storage/shared-buckets/` => 403

**Comment by Halama** [comment]
rekl bych asi ze standalone konzoli zrusime a nahradime ji jenom nejakym rozhradnim pro externi upload souboru - imho jediny jeji use case.
