### ISSUE TITLE
Remove bucket attributes

### ISSUE THREAD

**Issue by ujovlado** [keboola/storage-api-console#38]
Pridavanie bucket attributes nefunguje, takze to myslim mozeme vyhodit. Ani neviem na co to bolo.

Kuknem to a pri najhorsom tam necham len ich zoznam.

![screenshot_2017-10-10_17-24-26](https://user-images.githubusercontent.com/419849/31394970-eb817c18-addf-11e7-9443-331653a30efe.png)

**Comment by pivnicek** [comment]
just #fyi some legacy configurations used this in context with sys tables

**Comment by ujovlado** [comment]
@pivnicek thanks, I definitely need to explore it more :) Just noticed it's not working (adding new attributes). I think we can safely disable feature of adding and allow only list. If someone hit "the issue" he need to add/change, that's notice he's using something really old.

**Comment by Halama** [comment]
there is a youtube extractor still configured by attributes
