### ISSUE TITLE
Mis-aligned titles

### ISSUE THREAD

**Issue by pivnicek** [keboola/storage-api-console#46]
![image](https://user-images.githubusercontent.com/569139/35850075-f9690782-0b23-11e8-8f12-d2b70e006760.png)

**Comment by pivnicek** [comment]
It's fine in the console stand-alone, but not in connection.

**Comment by pivnicek** [comment]
This css looks like the culprit, only applies to the first div

![image](https://user-images.githubusercontent.com/569139/35850422-154466b2-0b25-11e8-82ad-4f02146fa019.png)

**Comment by Halama** [comment]
thanks!
