### ISSUE TITLE
Time Travel missing icon

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/storage-api-console#48]
Cleared cache, reloaded page, still missing.

![image](https://user-images.githubusercontent.com/497675/35859053-eacabd90-0b3e-11e8-9427-1643b80b34f0.png)

Btw. I would rename the modal title from `Restore table using time travel` to `Restore table using Snowflake Time Travel`, that's how they call the feature. 

And `Time Travel Restore` to `Snowflake Time Travel Restore` 

![image](https://user-images.githubusercontent.com/497675/35859131-32d0b798-0b3f-11e8-8c3d-7aba589c5537.png)

**Comment by Halama** [comment]
It is the name of our feature. We were discussing it there https://github.com/keboola/storage-api-console/pull/40#issuecomment-362619371

**Comment by ondrejhlavacek** [comment]
Ok, the copying from Snowflake confused me.

**Comment by Halama** [comment]
fixnuto tady https://github.com/keboola/storage-api-console/commit/ea4edb8a7d32de15fca7d318362f6bc4a26ced83

**Comment by Halama** [comment]
jeste neni nasazeno

**Comment by Halama** [comment]
nasazeno
