### ISSUE TITLE
Login - endpoint selector

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-console#55]
Zobrazovat defaultně výběr regionu.
https://www.dropbox.com/s/c0roki0cqo65n8b/Screenshot%202018-05-09%2021.24.08.png?dl=0

**Comment by Halama** [comment]
Mozná by to taky mohl být select s nabídkou endpointů.

**Comment by ujovlado** [comment]
Staci, ze sa na to odkazuje so spravnym endpointom.
