### ISSUE TITLE
Table and column delete - optional force param

### ISSUE THREAD

**Issue by ErikZigo** [keboola/storage-api-console#57]
- [x] Confirm pro smazani sloupce a tabulky se nahradi modalem.

  Modal se bude chovat stejne pokud tabulka nema alias a neni v bucketu ktery by byl nekam nalinkovany.

  - [x] V opacnem pripade se zobrazi info o aliasech + checkbox pro `force` delete.
Tlacitko `Delete` nepujde stisknout dokud neni checkbox zaskrtnuty.

Je tu jeste specialni pripad v situaci, kdy se maze sloupec ktery je pouzity u aliasu v `alliasColumns` nebo `aliasFilter`. V tom pripade by i smazani s `force` parametrem skoncilo chybou.

- [x] Zamezil bych tomu tak, ze misto ikony pro smazani sloupce se v UI zobrazi preskrtnuta ikona s tooltipem.

![image](https://user-images.githubusercontent.com/1726727/41660377-2b606b36-749c-11e8-8ef5-3005d1e52a1b.png)

- [x] Do detailu tabulky bych pridal seznam aliasu ktere tabulka ma

**Comment by Halama** [comment]
k tomu nám ale chybí ještě to info o aliasech ne?

**Comment by ErikZigo** [comment]
ty si chci vyfiltrovat ze seznamu tabulek

**Comment by Halama** [comment]
nojo ale tam nebudou aliasy do jiných projektů. Myslím že by to měl vrátit backend.

**Comment by Halama** [comment]
aha my už to tam máme teď `linkedBuckets`, to jsem úplně zapomněl

**Comment by ErikZigo** [comment]
Vim nalinkovane buckety a kazda tabulka je v tom nalinkovanem bucketu automaticky dostupna.

Mit v api neco podobneho u tabulek bych nechal asi az na to pokud budeme umoznovat i sdileni aliasu, pripadne alias z aliasu.

**Comment by ErikZigo** [comment]
Ted v seznamu bucketu vracime `linkedBy`, tak z toho jsem to vzal.

**Comment by Halama** [comment]
jo jasny, zapomněl jsem na ty linked bucket a to stačí v pohodě na tohle

**Comment by ErikZigo** [comment]
A taky si nejsem uplne jisty jestli by neco takoveho melo byt v API. I to `linkedBy` mi spis sedi do metadat.

**Comment by Halama** [comment]
me to do API sedi ale zatim to delat nemusime
