### ISSUE TITLE
Change Sharing Type

### ISSUE THREAD

**Issue by Halama** [keboola/storage-api-console#67]
Souvisí s https://github.com/keboola/connection/issues/1515

Aktuálně nabízíime u Shared bucketu pouze možnost zrušit sdílení a to pouze v případě že nebyl tento bucket nikam nalinkován.
![image](https://user-images.githubusercontent.com/903531/45736617-c1ec5600-bbeb-11e8-8c53-bce5a238a458.png)

Nově by mělo být možné typ sdílení změnit stejným způsobem jako když se bucket nastavuje jako sdílený. Asi tam přidat tlačítko `Change Sharing Type`?  Typ sdílení půjde adminem orgranizace změnit vždy nezávisle na tom jestli už někam byl nalinkován nebo ne.

![image](https://user-images.githubusercontent.com/903531/45736645-d892ad00-bbeb-11e8-897e-7df693c2518b.png)

**Comment by Actimel** [comment]
Prozatim je to sekle na rozbitem stacku https://github.com/keboola/storage-api-console/issues/68

**Comment by Halama** [comment]
done
