### ISSUE TITLE
SAPI console - private attributes

### ISSUE THREAD

**Issue by padak** [keboola/storage-api-console#9]
Pokud vyedituju privatní attribut, zůstane už neprivátní a je navěky vidět jeho hodnota.

**Comment by Halama** [comment]
to je feature

**Comment by padak** [comment]
dřív "se to stalo" zámečkem - jakej je smysl týhle vlastnosti?


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by Halama** [comment]
takhle to je uz od zacatku, overim to teda jestli se to nechova nejak jinak

**Comment by Halama** [comment]
aha sakra, tak to je nejakej bug v konzoli tomu  sebere protected flag.

**Comment by padak** [comment]
jj, to jsem se snažil popsat. dřiv stačilo reloadnout stránku a zas to bylo
vidět jako zámeček. dneska to zůstane odemknutý


--
Petr Simecek
+420 777 942 927

Blog http://padak.keboola.com/
Twitter https://twitter.com/petrsimecek
LinkedIn: http://linkd.in/simecekpetr
Calendar: http://bit.ly/petrsimecek

**Comment by Halama** [comment]
zaviram, atributy jsou deprecated
